### PR TITLE
autoload on server side mode

### PR DESCRIPTION
**Pull request by renatotkr**
auto-load="true" -> loads data on first request
Default  = false

### CODE REVIEW

**Comment by MoonStorm** [comment]
What's the purpose of this feature?

**Comment by renatotkr** [comment]
Hi moonstorm,

It's a little implementation I did to prevent loading data on grid load when in server side mode. This is useful for pages where I do not want data to be loaded before an user action.

**Comment by MoonStorm** [comment]
Isn't that fully under your control anyway? The grid doesn't fetch any data, it just asks you to do it via the callback.

**Comment by renatotkr** [comment]
yes, I can do this other ways. I just think that it will be easier to just put a tag. from what I saw in your amazing component code, server side mode is enabled when you specify onDataRequired and the callback is fired when you load the grid, so putting this tag disable the first data retrieval.

Anyways, I just did a quick code change, It's your call

thanks for the effort man, keep it up

cheers

**Comment by MoonStorm** [comment]
Cool thanks.

**Pull request closed without merging**
